import { calculateNEWS2 } from "./news2";

export type ScribePatient = {
  name: string;
  gender: string;
  medicalHistory?: string[];
};

export type ScribeEncounter = {
  chiefComplaint: string;
  acuity: number;
  vitals: Parameters<typeof calculateNEWS2>[0];
};

export type ScribeOrder = {
  testName: string;
};

export type NoteType = "SOAP" | "PROCEDURE" | "NURSING";

// ─── Legacy export kept for backwards compatibility ────────────────────────
export function generateScribeNote(
  patient: ScribePatient,
  encounter: ScribeEncounter,
  orders: ScribeOrder[]
) {
  return generateEnhancedNote(patient, encounter, orders, "", "SOAP");
}

/**
 * Generates a rich clinical note by weaving together structured EMR data and
 * any free-text spoken transcript captured via the Ambient Scribe microphone.
 */
export function generateEnhancedNote(
  patient: ScribePatient,
  encounter: ScribeEncounter,
  orders: ScribeOrder[],
  transcript: string = "",
  noteType: NoteType = "SOAP"
) {
  const news2 = calculateNEWS2(encounter.vitals);
  const ts = new Date().toLocaleString("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
  });
  const stability = news2.score >= 5 ? "UNSTABLE" : "STABLE";
  const monitorFreq = news2.score >= 5 ? "Q15min" : "Q1h";
  const orderList =
    orders.length > 0
      ? orders.map((o) => `• ${o.testName}`).join("\n    ")
      : "• None currently ordered";
  const pmhx =
    patient.medicalHistory?.length
      ? patient.medicalHistory.join(", ")
      : "No significant past medical history on file";

  // Spoken context line — only appended when a transcript was captured
  const dictationBlock =
    transcript.trim().length > 10
      ? `\n\nPROVIDER DICTATION (captured by Ambient Scribe):\n"${transcript.trim()}"\n`
      : "";

  if (noteType === "SOAP") {
    return `
PROGRESS NOTE
Date/Time: ${ts}
Provider: [Auto-generated — sign before submission]
ESI Acuity: Level ${encounter.acuity}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[S] SUBJECTIVE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Chief Complaint: ${encounter.chiefComplaint}
Past Medical History: ${pmhx}${dictationBlock}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[O] OBJECTIVE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Vital Signs
  Heart Rate   : ${encounter.vitals.hr} bpm
  Blood Pressure: ${encounter.vitals.bp} mmHg
  SpO2         : ${encounter.vitals.spO2}%
  Temperature  : ${encounter.vitals.temp}°F

Early Warning Score (NEWS2): ${news2.score} → Clinical Status: ${stability}

Active Orders:
    ${orderList}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[A] ASSESSMENT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${patient.name} is a ${patient.gender} presenting with ${encounter.chiefComplaint}.
Clinical trajectory is ${stability} per NEWS2 scoring.
Differential diagnoses under consideration based on presentation and available data.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[P] PLAN
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. Continue vital sign monitoring ${monitorFreq}.
2. Await results of ordered diagnostics and reassess.
3. Maintain ESI Level ${encounter.acuity} triage designation.
4. Patient/family education provided as appropriate.
5. [Provider: add additional plan elements here]

Electronically generated by Ambient AI Scribe — requires clinician review and co-signature.
    `.trim();
  }

  if (noteType === "PROCEDURE") {
    return `
PROCEDURE NOTE
Date/Time: ${ts}
Provider: [Auto-generated — sign before submission]
Patient: ${patient.name} | ESI Level ${encounter.acuity}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
INDICATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${encounter.chiefComplaint}
${dictationBlock}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PRE-PROCEDURE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Consent: Verbal consent obtained. Risks/benefits/alternatives discussed.
Timeout: Completed — patient identity, procedure site, and laterality confirmed.
Vital Signs at Start: HR ${encounter.vitals.hr} | BP ${encounter.vitals.bp} | O2 ${encounter.vitals.spO2}% | Temp ${encounter.vitals.temp}°F

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PROCEDURE DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Procedure: [Specify procedure name]
Technique: [Describe technique used]
Findings: [Document intra-procedure findings]
Complications: None encountered / [Document if applicable]
Specimens: None sent / [Document if applicable]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
POST-PROCEDURE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Patient tolerated procedure well. Vital signs stable post-procedure.
Follow-up plan: ${orders.length > 0 ? orders.map((o) => o.testName).join(", ") : "Reassess in 30 minutes"}.

Electronically generated by Ambient AI Scribe — requires clinician review and co-signature.
    `.trim();
  }

  // NURSING assessment note
  return `
NURSING ASSESSMENT NOTE
Date/Time: ${ts}
Nurse: [Auto-generated — sign before submission]
Patient: ${patient.name}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PRESENTING CONCERN
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Chief Complaint: ${encounter.chiefComplaint}
Past Medical History: ${pmhx}${dictationBlock}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
VITAL SIGNS REVIEW
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  HR: ${encounter.vitals.hr} bpm   |   BP: ${encounter.vitals.bp}
  SpO2: ${encounter.vitals.spO2}%  |   Temp: ${encounter.vitals.temp}°F
  NEWS2 Score: ${news2.score} (${stability})

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
NURSING ASSESSMENT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Neuro   : Alert and oriented × [3/4]. GCS assessed separately.
Resp    : ${encounter.vitals.spO2 < 94 ? "SpO2 below threshold — supplemental oxygen initiated." : "Breath sounds assessed. SpO2 within acceptable range."}
Cardiac : HR ${encounter.vitals.hr} bpm. Rhythm: [Document rhythm].
Pain    : Pain scale [0-10] — patient reports: [Document].
Skin    : [Document skin integrity/color/temperature].
Fall Risk: [Low / Medium / High — document basis].

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
NURSING INTERVENTIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${orderList}
• Patient and family education provided per ESI ${encounter.acuity} protocol.
• Physician notified of assessment findings.
• Monitoring frequency: ${monitorFreq}.

Electronically generated by Ambient AI Scribe — requires nurse review and co-signature.
  `.trim();
}