import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface Encounter {
  acuity: number;
  patientName: string;
  location?: string;
  chiefComplaint: string;
  vitals: {
    hr: number;
    bp: string;
    spO2: number;
  };
  status: string;
}

export const exportShiftReport = (encounters: Encounter[]) => {
  const doc = new jsPDF();
  const date = new Date().toLocaleDateString();

  // 1. HEADER
  doc.setFontSize(20);
  doc.setTextColor(40, 40, 40);
  doc.text("END-OF-SHIFT HANDOFF REPORT", 14, 22);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Facility: Hackensack Meridian - Unit 4B`, 14, 30);
  doc.text(`Date: ${date} | Generated by: Sophia Ramirez, CCMA`, 14, 35);

  // 2. DATA TABLE MAPPING
  const tableRows = encounters.map(e => [
    `ESI ${e.acuity}`,
    e.patientName,
    e.location || "Triage Queue",
    e.chiefComplaint,
    `${e.vitals.hr} | ${e.vitals.bp} | ${e.vitals.spO2}%`,
    e.status.toUpperCase()
  ]);

  // 3. GENERATE TABLE
  autoTable(doc, {
    startY: 45,
    head: [['ESI', 'Patient Name', 'Bed/Loc', 'Chief Complaint', 'Vitals (HR/BP/O2)', 'Status']],
    body: tableRows,
    theme: 'grid',
    headStyles: { fillColor: [30, 41, 59], textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    margin: { top: 45 },
  });

  // 4. FOOTER / LEGAL DISCLAIMER
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    const pageSize = doc.internal.pageSize;
    const pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight();
    doc.text(
      "CONFIDENTIAL PHI - SHRED AFTER USE. DO NOT LEAVE IN PUBLIC AREAS.",
      14,
      pageHeight - 10
    );
    doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.getWidth() - 30, pageHeight - 10);
  }

  doc.save(`Shift_Report_${date.replace(/\//g, '-')}.pdf`);
};