export const CLINICAL_REF = {
  LABS: [
    { name: "WBC", range: "4.5 - 11.0 x10³/µL", critical: "< 2.5 or > 30.0", note: "Indicator of infection or stress." },
    { name: "Potassium (K+)", range: "3.5 - 5.0 mEq/L", critical: "< 2.5 or > 6.5", note: "High risk for cardiac arrhythmia." },
    { name: "Hemoglobin (Hgb)", range: "M: 13.8-17.2 | F: 12.1-15.1", critical: "< 7.0", note: "Transfusion threshold is usually 7.0." },
    { name: "Sodium (Na+)", range: "135 - 145 mEq/L", critical: "< 120 or > 160", note: "Neurological status risk." },
    { name: "Glucose", range: "70 - 99 mg/dL (fasting)", critical: "< 40 or > 400", note: "Risk of hypoglycemia or hyperglycemic crisis." },
    { name: "Creatinine", range: "0.6 - 1.2 mg/dL", critical: "> 4.0", note: "Indicates severe renal impairment." },
    { name: "Troponin", range: "< 0.04 ng/mL", critical: "> 0.40 ng/mL", note: "Highly specific for myocardial injury." },
    { name: "Lactate", range: "0.5 - 2.2 mmol/L", critical: "> 4.0", note: "Marker of tissue hypoperfusion and sepsis." },
    { name: "D-dimer", range: "< 500 ng/mL FEU", critical: "> 2000 ng/mL FEU", note: "Elevated in thrombotic events, but non-specific." },
    { name: "CRP", range: "< 10 mg/L", critical: "> 100 mg/L", note: "Marker of inflammation, elevated in severe infections." },
    { name: "ESR", range: "0 - 20 mm/hr", critical: "> 100 mm/hr", note: "Non-specific marker of inflammation, elevated in severe infections." },
    { name: "BNP", range: "< 100 pg/mL", critical: "> 500 pg/mL", note: "Elevated in heart failure, but non-specific." },
    { name: "ALT", range: "7 - 56 U/L", critical: "> 300 U/L", note: "Indicates severe liver injury." },
    { name: "AST", range: "10 - 40 U/L", critical: "> 300 U/L", note: "Indicates severe liver injury." },
    { name: "Alkaline Phosphatase", range: "44 - 147 U/L", critical: "> 500 U/L", note: "Elevated in biliary obstruction or severe liver disease." },
    { name: "Total Bilirubin", range: "0.1 - 1.2 mg/dL", critical: "> 5.0 mg/dL", note: "Indicates severe liver dysfunction or hemolysis." },
    { name: "Amylase", range: "23 - 85 U/L", critical: "> 300 U/L", note: "Elevated in acute pancreatitis." },
    { name: "Lipase", range: "0 - 160 U/L", critical: "> 300 U/L", note: "More specific than amylase for pancreatitis." },
    { name: "Procalcitonin", range: "< 0.1 ng/mL", critical: "> 2.0 ng/mL", note: "Marker of bacterial infection and sepsis." },
    { name: "INR", range: "0.8 - 1.2 (not on anticoagulants)", critical: "> 5.0", note: "High risk of bleeding." },
    { name: "PTT", range: "25 - 35 seconds", critical: "> 70 seconds", note: "High risk of bleeding." },
    { name: "Platelets", range: "150 - 450 x10³/µL", critical: "< 50 or > 1000", note: "Risk of bleeding or thrombosis." },
    { name: "Bun", range: "7 - 20 mg/dL", critical: "> 100 mg/dL", note: "Indicates severe renal impairment." },
    { name: "GFR", range: "> 90 mL/min/1.73m²", critical: "< 15 mL/min/1.73m²", note: "Indicates end-stage renal disease." },
    { name: "HbA1c", range: "< 5.7%", critical: "> 9.0%", note: "Indicates poor long-term glucose control." },
  ],
  VITALS: [
    { name: "BP", range: "120/80", critical: "> 180/120 (Crisis)", note: "Hypertensive Crisis requires immediate IV meds." },
    { name: "O2 Sat", range: "95% - 100%", critical: "< 90%", note: "Consider O2 for anything under 94% in ER." },
    { name: "HR", range: "60 - 100 bpm", critical: "< 50 or > 120 bpm", note: "Bradycardia or tachycardia may require intervention." },
    { name: "Temp", range: "97°F - 99°F", critical: "< 95°F or > 104°F", note: "Hypothermia or hyperthermia can be life-threatening." },
    { name: "Resp Rate", range: "12 - 20 breaths/min", critical: "< 8 or > 30 breaths/min", note: "Bradypnea or tachypnea may indicate respiratory distress." },
  ]
};