export const MEDICATION_DATABASE = [
  { name: "Amoxicillin", class: "Penicillin", dose: "500mg", route: "PO" },
  { name: "Cephalexin", class: "Cephalosporin", dose: "250mg", route: "PO" },
  { name: "Ibuprofen", class: "NSAID", dose: "400mg", route: "PO" },
  { name: "Morphine", class: "Opioid", dose: "2mg", route: "IV" },
  { name: "Lisinopril", class: "ACE Inhibitor", dose: "10mg", route: "PO" },
  { name: "Metformin", class: "Biguanide", dose: "500mg", route: "PO" },
  { name: "Aspirin", class: "Antiplatelet", dose: "81mg", route: "PO" },
  { name: "Albuterol", class: "Beta-2 Agonist", dose: "90mcg", route: "Inhalation" },
  { name: "Warfarin", class: "Anticoagulant", dose: "5mg", route: "PO" },
  { name: "Prednisone", class: "Corticosteroid", dose: "20mg", route: "PO" },
  { name: "Progesterone", class: "Hormone", dose: "200mg", route: "PO" },
  { name: "Estradiol", class: "Hormone", dose: "2mg", route: "Sublingual" },
  { name: "Spironolactone", class: "Diuretic", dose: "25mg", route: "PO" },
  { name: "Furosemide", class: "Diuretic", dose: "40mg", route: "IV" },
  { name: "Sertraline", class: "SSRI", dose: "50mg", route: "PO" },
  { name: "Fluoxetine", class: "SSRI", dose: "20mg", route: "PO" },
  { name: "Fluvoxamine", class: "SSRI", dose: "50mg", route: "PO" },
  { name: "Paroxetine", class: "SSRI", dose: "20mg", route: "PO" },
  { name: "Citalopram", class: "SSRI", dose: "20mg", route: "PO" },
  { name: "Escitalopram", class: "SSRI", dose: "10mg", route: "PO" },
  { name: "Adderall", class: "Stimulant", dose: "10mg", route: "PO" },
  { name: "Ritalin", class: "Stimulant", dose: "10mg", route: "PO" },
  { name: "Vyvanse", class: "Stimulant", dose: "30mg", route: "PO" },
  { name: "Concerta", class: "Stimulant", dose: "18mg", route: "PO" },
  { name: "Strattera", class: "Non-Stimulant", dose: "40mg", route: "PO" },
  { name: "Guanfacine", class: "Non-Stimulant", dose: "1mg", route: "PO" },
  { name: "Clonidine", class: "Non-Stimulant", dose: "0.1mg", route: "PO" },
  { name: "Atomoxetine", class: "Non-Stimulant", dose: "40mg", route: "PO" },
  { name: "Bupropion", class: "Non-Stimulant", dose: "150mg", route: "PO" },
  { name: "Lithium", class: "Mood Stabilizer", dose: "300mg", route: "PO" },
  { name: "Valproate", class: "Mood Stabilizer", dose: "500mg", route: "PO" },
  { name: "Carbamazepine", class: "Mood Stabilizer", dose: "200mg", route: "PO" },
  { name: "Lamotrigine", class: "Mood Stabilizer", dose: "100mg", route: "PO" },
  { name: "Topiramate", class: "Mood Stabilizer", dose: "50mg", route: "PO" },
  { name: "Olanzapine", class: "Antipsychotic", dose: "10mg", route: "PO" },
  { name: "Risperidone", class: "Antipsychotic", dose: "2mg", route: "PO" },
  { name: "Quetiapine", class: "Antipsychotic", dose: "25mg", route: "PO" },
  { name: "Aripiprazole", class: "Antipsychotic", dose: "10mg", route: "PO" },
  { name: "Ziprasidone", class: "Antipsychotic", dose: "20mg", route: "PO" },
  { name: "Tenecteplase", class: "Thrombolytic", dose: "50mg", route: "IV" },
  { name: "Testosterone", class: "Hormone", dose: "50mg", route: "IM" },
  { name: "Insulin", class: "Hormone", dose: "10 units", route: "SC" },
  { name: "Metoprolol", class: "Beta Blocker", dose: "50mg", route: "PO" },
  { name: "Timolol", class: "Beta Blocker", dose: "10mg", route: "PO" },
  { name: "Propranolol", class: "Beta Blocker", dose: "40mg", route: "PO" },
  { name: "Atenolol", class: "Beta Blocker", dose: "25mg", route: "PO" },
  { name: "Carvedilol", class: "Beta Blocker", dose: "25mg", route: "PO" },
  { name: "Labetalol", class: "Beta Blocker", dose: "100mg", route: "PO" },
  { name: "Nebivolol", class: "Beta Blocker", dose: "5mg", route: "PO" },
  { name: "Bisoprolol", class: "Beta Blocker", dose: "10mg", route: "PO" },
  { name: "Desvenlafaxine", class: "SNRI", dose: "50mg", route: "PO" },
  { name: "Duloxetine", class: "SNRI", dose: "60mg", route: "PO" },
  { name: "Venlafaxine", class: "SNRI", dose: "75mg", route: "PO" },
  { name: "Levetiracetam", class: "Antiepileptic", dose: "500mg", route: "PO" },
  { name: "Gabapentin", class: "Antiepileptic", dose: "300mg", route: "PO" },
  { name: "Pregabalin", class: "Antiepileptic", dose: "150mg", route: "PO" },
  { name: "Phenytoin", class: "Antiepileptic", dose: "100mg", route: "PO" },
  { name: "Valproic Acid", class: "Antiepileptic", dose: "500mg", route: "PO" },
  { name: "Telithromycin", class: "Macrolide", dose: "800mg", route: "PO" },
  { name: "Azithromycin", class: "Macrolide", dose: "250mg", route: "PO" },
  { name: "Erythromycin", class: "Macrolide", dose: "500mg", route: "PO" },
  { name: "Clarithromycin", class: "Macrolide", dose: "500mg", route: "PO" },
  { name: "Fidaxomicin", class: "Macrolide", dose: "200mg", route: "PO" },
  { name: "Doxycycline", class: "Tetracycline", dose: "100mg", route: "PO" },
  { name: "Tetracycline", class: "Tetracycline", dose: "500mg", route: "PO" },
  { name: "Minocycline", class: "Tetracycline", dose: "100mg", route: "PO" },
  { name: "Tigecycline", class: "Tetracycline", dose: "100mg", route: "IV" },
  { name: "Demeclocycline", class: "Tetracycline", dose: "150mg", route: "PO" },
  { name: "Acetaminophen", class: "Analgesic/Antipyretic", dose: "650mg", route: "PO" },
  { name: "Ketorolac", class: "NSAID", dose: "15mg", route: "IV" },
  { name: "Ondansetron", class: "Antiemetic", dose: "4mg", route: "IV" },
  { name: "Metoclopramide", class: "Antiemetic", dose: "10mg", route: "IV" },
  { name: "Diphenhydramine", class: "Antihistamine", dose: "25mg", route: "IV" },
  { name: "Epinephrine", class: "Sympathomimetic", dose: "0.3mg", route: "IM" },
  { name: "Nitroglycerin", class: "Nitrate", dose: "0.4mg", route: "SL" },
  { name: "Heparin", class: "Anticoagulant", dose: "5000 units", route: "IV" },
  { name: "Enoxaparin", class: "Anticoagulant", dose: "40mg", route: "SC" },
  { name: "Ceftriaxone", class: "Cephalosporin", dose: "1g", route: "IV" },
  { name: "Vancomycin", class: "Glycopeptide", dose: "1000mg", route: "IV" },
  { name: "Piperacillin-Tazobactam", class: "Penicillin Combination", dose: "4.5g", route: "IV" },
  { name: "Ipratropium", class: "Anticholinergic Bronchodilator", dose: "0.5mg", route: "Inhalation" },
  { name: "Methylprednisolone", class: "Corticosteroid", dose: "125mg", route: "IV" },
  { name: "Lorazepam", class: "Benzodiazepine", dose: "1mg", route: "IV" },
  { name: "Haloperidol", class: "Antipsychotic", dose: "5mg", route: "IM" },
  { name: "Dextrose 50%", class: "Hypoglycemia Rescue", dose: "25g", route: "IV" },
  { name: "Glucagon", class: "Hypoglycemia Rescue", dose: "1mg", route: "IM" },
  { name: "Pantoprazole", class: "Proton Pump Inhibitor", dose: "40mg", route: "IV" },
  { name: "Famotidine", class: "H2 Blocker", dose: "20mg", route: "IV" },
];

export function checkAllergyConflict(medName: string, patientAllergies: string[]): string | null {
  const med = MEDICATION_DATABASE.find(m => m.name === medName);
  if (!med) return null;

  // Check if the medication name or its class matches an allergy
  const conflict = patientAllergies.find(allergy => 
    med.name.toLowerCase().includes(allergy.toLowerCase()) ||
    med.class.toLowerCase().includes(allergy.toLowerCase())
  );

  return conflict ? `Conflict detected: Patient is allergic to ${conflict}.` : null;
}